### ISSUE TITLE
i want to create my own account

### ISSUE THREAD

**Issue by llemonex** [foxssake/netfox#138] opened 2023-11-25 03:25 UTC
i want to register as a new account and type my thing to "noray host" line then it gives me my own open id right ? but i cant :) how can i create my own acc instead of using"tomfol.io:8890" or am i wrong and thought wrong? please make a youtube tutorial and showcase and explain everthing and what is this for bcs i really dont understand

**Comment by elementbound** [comment] 2023-11-25 10:13
Hi @llemonex, thanks for trying Forest Brawl! 
I'm not sure I follow your question. Is it about how to host and join a game over noray, or is it about hosting your own noray server?

For hosting and joining a game with noray, here's a very quick video to demonstrate, hope it adds enough extra info to the [README](https://github.com/foxssake/netfox/tree/main/examples/forest-brawl): <https://youtu.be/BlH2IWxZpk0>

For running your own noray server, you'll need a dedicated host machine, optionally with a domain registered.

Let me know if I answered your question!

**Comment by Ughuuu** [comment] 2023-11-26 10:11
Are we allowed to use your domain for nat punch through? eg tomfol.io? Or is that too much to ask.

**Comment by elementbound** [comment] 2023-11-26 10:46
@Ughuuu feel free to use the noray instance at tomfol.io! Especially for prototyping or testing stuff. For actually shipping your game, I wouldn't recommend it, as that instance has stricter limits configured, and I can't give any guarantees on availability or performance.
I'm happy to maintain that instance as long as people don't mis/abuse it.

**Comment by Ughuuu** [comment] 2023-11-26 10:48
That's perfect, for testing purposes was my thought.

**Comment by Ughuuu** [comment] 2023-11-26 11:47
I think the confusion of @llemonex comes from the fact that it seems that that tomfol.io:8890 is an account. While it's a hosted instance that can be used in testing. Also, if you go to Noray documentation it takes you back to the documentation. It's not immediately obvious what are the steps needed to use Noray: eg. you need a hosted instance of Noray, you need to bind it to a hostname, you need to enable a port, and then you need to point the client to that hostname:port.(or use tomfol.io:8890 for testing purposes)

**Comment by Ughuuu** [comment] 2023-11-27 13:35
On this also, not sure what happened but now I get timeouts from "tomfol.io:8890". Am courious if something happened to the server, or if it ran out of ports, etc.

**Comment by elementbound** [comment] 2023-11-27 16:30
@Ughuuu the noray instance did restart around the time of your comment. Not sure of the cause yet, but doesn't seem like a major issue at the moment, but will keep an eye on it.

**Comment by elementbound** [comment] 2023-11-28 17:12
Closing issue. @llemonex please feel free to comment in case we didn't cover your need!

**Closed** 2023-11-28 17:14 UTC
