### ISSUE TITLE
netfox downloaded to res:// instead of res://addons

### ISSUE THREAD

**Issue by zibetnu** [foxssake/netfox#140] opened 2023-11-25 18:59 UTC
I downloaded the netfox addon from the in-editor AssetLib to start using it in a project, and it was downloaded to `res://` instead of `res://addons`. Is this intentional?

**Comment by elementbound** [comment] 2023-11-25 20:52
No, it's something I've noticed myself recently as well. I'm not sure why though, the zip linked on the asset page contains an addons directory. Will look into it.

**Comment by Ughuuu** [comment] 2023-11-26 10:09
As a fix for now you can uncheck the Ignore Asset Root
<img width="621" alt="image" src="https://github.com/foxssake/netfox/assets/2369380/4c859176-7ecc-451a-b286-2a720d049d67">

**Comment by elementbound** [comment] 2023-11-26 11:01
Submitted the edits on the asset library, we'll see if the issue is fixed once the asset library people approve the changes.

**Comment by elementbound** [comment] 2023-11-28 10:22
Version 1.0.1 is approved on the asset library. Issue is fixed.

**Closed by elementbound** 2023-11-28 10:22 UTC
